"""country

Revision ID: a5ff81a1a349
Revises: bddd0fb917e0
Create Date: 2023-04-02 04:10:20.339715

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "a5ff81a1a349"
down_revision = "bddd0fb917e0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "country",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("author", sa.Column("middle_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("author", sa.Column("patronymic", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("author", sa.Column("country_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "author", "country", ["country_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "author", type_="foreignkey")
    op.drop_column("author", "country_id")
    op.drop_column("author", "patronymic")
    op.drop_column("author", "middle_name")
    op.drop_table("country")
    # ### end Alembic commands ###
